# Copyright (C) 2011 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/a7xltechn/setup-makefiles.sh

# Prebuilt libraries that are needed to build open-source libraries
#vendor/samsung/a7xltechn/proprietary/lib/libcamera.so:obj/lib/libcamera.so \
#vendor/samsung/a7xltechn/proprietary/lib/libcameraservice.so:obj/lib/libcameraservice.so \
#vendor/samsung/a7xltechn/proprietary/lib/libcamera_client.so:obj/lib/libcamera_client.so \
#vendor/samsung/a7xltechn/proprietary/lib/liboemcamera.so:obj/lib/liboemcamera.so \

PRODUCT_COPY_FILES += \
vendor/samsung/a7xltechn/proprietary/lib/libaudioalsa.so:obj/lib/libaudioalsa.so \
 vendor/samsung/a7xltechn/proprietary/vendor/lib/libtar.so:system/vendor/lib/libtar.so
